### ISSUE TITLE
rounds extending due to this plugin

### ISSUE THREAD

**Issue by flashing1998** [b3none/retakes-instadefuse#16]
due to your instadefuse plugin rounds are exending even the max rounds limit is 30

**Comment by gabriel3l** [comment]
can confirm.

**Comment by b3none** [comment]
This has been a bug with instadefuse for some time and I’ve tried to fix it a couple of times. What I’ll do for now is write a crude check to force end the match based on the maxrounds set.

**Comment by gabriel3l** [comment]
I am quite curious about what happens.
Does the server not 'fully' register the rounds, so it goes on past the maxrounds thinking some rounds had never been played, or what?

**Comment by borzaka** [comment]
Yes, this fix has some side effects;
- When the game ends, and the scoreboard comes in, you can still move/shoot.
- It disables somehow the native map voting.

Without this plugin, the game "freezes" you at the game end, and you can use the map voting.

**Comment by shaikhnedab** [comment]
also it is preventing item drops at the match end.

**Comment by flashing1998** [comment]
https://forums.alliedmods.net/showthread.php?t=313815
Use this instead

**Comment by shaikhnedab** [comment]
Thank you very much.

**Comment by b3none** [comment]
Let me know if you can do some testing and figure out what the issue is, i'd be happy to accept an update! :)

**Comment by b3none** [comment]
> https://forums.alliedmods.net/showthread.php?t=313815
> Use this instead

As opposed to using this you could look at using an earlier release of this plugin too.

**Comment by shaikhnedab** [comment]
i am ready to test your plugin please add me at 
https://steamcommunity.com/id/shaikhnedab
