### ISSUE TITLE
Latest update breaks it

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [b3none/retakes-instadefuse#18]
Latest update seems to break Retakes. I cant join team when using it. No errors from what I can see.

**Comment by b3none** [comment]
This is a strange one! I'll spend some time testing it and see if I can get to the route of the problem. This shouldn't really cause problems with that. As far as I am aware not being able to join a team is a regular retakes issue. i.e. selecting a team and having to press the `esc` key.

**Comment by BrutalCSEjziponken** [comment]
Hm, well maybe the teamselect is a different problem but this version still breaks retakes since I had no players on any of my servers and now I have when i removed it :D


VladeToday at 15:10
maps are just realoading after warmup

**Comment by b3none** [comment]
Is this for version `1.4.0`? @BrutalCSEjziponken
