### ISSUE TITLE
CT Wins are not counting in total Rounds

### ISSUE THREAD

**Issue by shaikhnedab** [b3none/retakes-instadefuse#19]
Hello
I am hosting a retake server. Issue is that CT rounds wins are not getting counted in Total Rounds oj Tab menu scoreboard. 
for example if score is CT 5 Wins and T 4 Wins in tab menu scoreboard it will only count 4 T Wins. 
Because of that total Rounds goes beyond 30 till T side wins 30 (mp_maxrounds is already set to 30 and then map change takes place). 
This only happens when this plugin is enabled. 
Can you look into it. 
[pluginslist.txt](https://github.com/b3none/retakes-instadefuse/files/3602140/pluginslist.txt)

attaching my plugins list.

**Comment by GTAmama16** [comment]
yep having the same problem 
hope it can get fix :D

**Comment by b3none** [comment]
That's a very strange problem, however, I think it's one that we could solve together! Would you like to do some testing with me this weekend to see if we can get to the bottom of this?

My Steam is: https://steamcommunity.com/id/b3none

**Comment by GTAmama16** [comment]
yeah just added ya :D

**Comment by shaikhnedab** [comment]
found the solution. just compile 1.4.0 version of insta defuse here on github and it will work fine. earlier version of insta defuse is the one causing this issue.

**Comment by b3none** [comment]
Oh brilliant, in that case I'll make a release for version 1.4.0 -- Let me know if you run into any problems and we can get them patched.

**Comment by shaikhnedab** [comment]
sure :).
