### ISSUE TITLE
The plugin is still working, although I have put it in a disabled folder.

### ISSUE THREAD

**Issue by Ongz1337** [b3none/retakes-instadefuse#23]
I have successfully taken the plugin into the disabled folder.
But when typing sm plugins refresh on the console, it shows that the plugin is still working on the list.
I have tried typing sm plugins reload retakes_instadefuse.smx in the console, the result shows that [SM] Plugin retakes_instadefuse.smx is not loaded.

Picture of the bug: http://prntscr.com/pq9kr8

**Comment by b3none** [comment]
If you'd like to run this plugin on your server it shouldn't be in the `disabled` folder. Can you make sure that you've definitely called it `retakes_instadefuse.smx`. I'm struggling to understand the problem here. Is the plugin not loading?

**Comment by Ongz1337** [comment]
I will just temporarily disable it. But when I added it to the disabled folder and finished refreshing the plug-in
retakes_instadefuse.smx Still works in the list of sm plugins list

**Comment by b3none** [comment]
I'm confident this isn't a problem with the plugin. I think you're misunderstanding how SourceMod works. I am pretty sure SourceMod loads the plugins on map start and then caches them for the duration of the map.
