### ISSUE TITLE
Map Vote issue

### ISSUE THREAD

**Issue by gouyeh** [B3none/retakes-instadefuse#24]
Hello, End of the match map votes are not showing auto changing to random map.
When disable this plugin map votes are working. Please fix thiss

**Comment by Roy47Zhang** [comment]
same issue

**Comment by zahti** [comment]
I have the same exact issue with the latest release 1.4.0. @b3none Any ideas for what to try? 

**When plugin is _loaded_:**
- Unintentionally skips the default scoreboard map-vote &#x1F534;
- Here are the console messages displayed at end of match:

```
May  1 20:10:51:  L 05/01/2020 - 20:10:51: World triggered "Round_Start"
May  1 20:10:52:  L 05/01/2020 - 20:10:52: "Zahti<2><STEAM_1:1:16728297><TERRORIST>" triggered "Planted_The_Bomb"
May  1 20:11:33:  L 05/01/2020 - 20:11:33: Team "TERRORIST" triggered "SFUI_Notice_Target_Bombed" (CT "0") (T "1")
May  1 20:11:33:  L 05/01/2020 - 20:11:33: Team "CT" scored "0" with "0" players
May  1 20:11:33:  L 05/01/2020 - 20:11:33: Team "TERRORIST" scored "1" with "1" players
May  1 20:11:33:  L 05/01/2020 - 20:11:33: World triggered "Round_End"
May  1 20:11:33:  L 05/01/2020 - 20:11:33: "Zahti<2><STEAM_1:1:16728297><TERRORIST>" [-81 -1362 1723] was killed by the bomb.
May  1 20:11:58:  CHANGELEVEL: Looking for next level in mapgroup 'mg_retakes'
May  1 20:11:58:  Looking for next map in mapgroup 'mg_retakes'...
May  1 20:11:58:  CHANGELEVEL: Choosing map 'de_dust2' (previous was de_cache)
May  1 20:11:58:  CHANGELEVEL: Looking for next level in mapgroup 'mg_retakes'
May  1 20:11:58:  Looking for next map in mapgroup 'mg_retakes'...
May  1 20:11:58:  CHANGELEVEL: Choosing map 'de_dust2' (previous was de_cache)
May  1 20:11:58:  CHANGE LEVEL: de_dust2
May  1 20:11:58:  RecordSteamInterfaceCreation (PID 13): SteamGameStats001 /
May  1 20:11:58:  message repeated 2 times: [ RecordSteamInterfaceCreation (PID 13): SteamGameStats001 /]
May  1 20:11:58:  L 05/01/2020 - 20:11:58: [META] Loaded 0 plugins (1 already loaded)
May  1 20:11:58:  ---- Host_Changelevel ----
May  1 20:11:58:  L 05/01/2020 - 20:11:58: [META] Loaded 0 plugins (1 already loaded)
May  1 20:11:58:  *** Map Load: de_dust2: Map Group mg_retakesL 05/01/2020 - 20:11:58: Log file closed
May  1 20:11:58:  Server logging data to file logfiles/L172_107_198_106_27041_202005012011_000.log
May  1 20:11:58:  L 05/01/2020 - 20:11:58: Log file started (file "logfiles/L172_107_198_106_27041_202005012011_000.log") (game "<dir>") (version "7803")
May  1 20:11:58:  L 05/01/2020 - 20:11:58: Loading map "de_dust2"
May  1 20:11:58:  L 05/01/2020 - 20:11:58: server cvars start
```

**When plugin is _unloaded_:**
- Properly triggers and uses the default scoreboard map-vote &#x1F535;
- Here are the console messages displayed at end of match:
```
May  1 20:17:55:  L 05/01/2020 - 20:17:55: rcon from "<ip redacted>": command "sm plugins list"
May  1 20:17:59:  L 05/01/2020 - 20:17:59: server_cvar: "nextlevel" "de_overpass"
May  1 20:18:04:  CHANGELEVEL: ConVar 'nextlevel' is set, next map will be 'de_overpass'
May  1 20:18:04:  CHANGE LEVEL: de_overpass
May  1 20:18:04:  RecordSteamInterfaceCreation (PID 13): SteamGameStats001 /
May  1 20:18:04:  message repeated 2 times: [ RecordSteamInterfaceCreation (PID 13): SteamGameStats001 /]
May  1 20:18:04:  L 05/01/2020 - 20:18:04: [META] Loaded 0 plugins (1 already loaded)
May  1 20:18:04:  ---- Host_Changelevel ----
May  1 20:18:04:  L 05/01/2020 - 20:18:04: [META] Loaded 0 plugins (1 already loaded)
May  1 20:18:04:  *** Map Load: de_overpass: Map Group mg_retakesL 05/01/2020 - 20:18:04: Log file closed
May  1 20:18:04:  Server logging data to file logfiles/L172_107_198_106_27041_202005012018_000.log
May  1 20:18:04:  L 05/01/2020 - 20:18:04: Log file started (file "logfiles/L172_107_198_106_27041_202005012018_000.log") (game "<dir>") (version "7803")
May  1 20:18:04:  L 05/01/2020 - 20:18:04: Loading map "de_overpass"
May  1 20:18:04:  L 05/01/2020 - 20:18:04: server cvars start
```
`rcon sm plugins list` (with plugin unloaded):
```
[SM] Listing 27 plugins:
  01 "Connect MSG" (1.0) by Crazy
  02 "[Retakes] Autoplant" (2.3.0) by B3none
  03 "RankMe" (3.0.3.Kento.31.4) by lok1, Scooby, Kento, pracc, Kxnrl, CrazyHackGUT
  04 "CS:GO Retakes" (0.3.4) by splewis
  05 "Reserved Slots" (1.10.0.6478) by AlliedModders LLC
  06 "hextags" (2.02) by Hexah
  07 "Advertisements" (2.0.3) by Tsunami
  08 "Chat Processor - Simple Chat Processor Wrapper" (1.0.0) by Keith Warren (Shaders Allen)
  09 "Chat-Processor" (2.2.2) by Drixevel
  10 "[Retakes] Bombsite HUD" (2.2.5) by B3none
  11 "CS:GO Retakes: Customised Weapon Allocator for splewis retakes plugin" (0.3.4) by BatMen, modified by tmerc
  12 "BlockRadio" (1.0) by cra88y
  13 "Sound Commands" (1.10.0.6478) by AlliedModders LLC
  14 "Admin Help" (1.10.0.6478) by AlliedModders LLC
  15 "Player Commands" (1.10.0.6478) by AlliedModders LLC
  16 "Basic Commands" (1.10.0.6478) by AlliedModders LLC
  17 "Admin Menu" (1.10.0.6478) by AlliedModders LLC
  18 "Basic Comm Control" (1.10.0.6478) by AlliedModders LLC
  19 "Client Preferences" (1.10.0.6478) by AlliedModders LLC
  20 "Basic Info Triggers" (1.10.0.6478) by AlliedModders LLC
  21 "Anti-Flood" (1.10.0.6478) by AlliedModders LLC
  22 "Basic Votes" (1.10.0.6478) by AlliedModders LLC
  23 "Fun Commands" (1.10.0.6478) by AlliedModders LLC
  24 "Fun Votes" (1.10.0.6478) by AlliedModders LLC
  25 "Admin File Reader" (1.10.0.6478) by AlliedModders LLC
  26 "Basic Ban Commands" (1.10.0.6478) by AlliedModders LLC
  27 "Basic Chat" (1.10.0.6478) by AlliedModders LLC
```

**Comment by Sarrus1** [comment]
I fixed this here: https://github.com/b3none/retakes-instadefuse/pull/32/commits/1b1a20c50f8571235fd5e231148b89ee17a8e70f

@gouyeh @RoyZ-CSGO @zahti

**Comment by e1xom** [comment]
@Sarrus1 The fix seems to work when I'm the sole player in the server, once there is more then 1 player in the server. The fix stopped working resulting in no mapvote at the end of the match and the server changing the map itself.

Any clues as to why and how to fix?

**Comment by Sarrus1** [comment]
@e1xom Are you sure you are using the latest code and not the latest release instead?

If not, make sure you have mp_team_can_clinch 0 (that's what I have at least).

Otherwise I don't know, this seems to be working on my servers, you can test it on [tensor.fr](http://tensor.fr).

**Comment by e1xom** [comment]
I took your fixed retakes_instadefuse.sp with 342 total lines of code and replaced the old retakes_instadefuse.sp 
Everything else is the same as it was from the latest release.

I'll try your command and see if that fixes it. Thank you for the super fast reply!

**Comment by Sarrus1** [comment]
Make sure you have a mapgroup set, and make sure that everything works without the plugin.

**Comment by e1xom** [comment]
Everything is working properly. I kept the amount of plugins running to a minimum on purpose.

Mapgroup is set and returns the proper value when using "print_mapgroup" 

For the instadefuse plugin I have the following:
retakes-instadefuse.smx (from the latest release)
retakes-instadefuse.sp (your fixed code)
all the translation files (from the latest release)

I don't understand why it stopped working. 

When I replaced the original retakes-instadefuse.sp with your code, I went into the server and used mp_maxrounds 1 to test and see if the votemap would come up at the end and it did.

A day later I connect with some friends to the server and the mapvote simply doesn't show up anymore. I haven't changed anything to the server in the meanwhile, neither have I added any other files or plugins.. 

So frustrating, it's the last thing I need to get working then the server is working flawlessly.

**Comment by e1xom** [comment]
Alright, so to sum it up to see if I understand completely.

I take your code from the .sp file, which I put into the Spider Compiler, then I compile it and download it.

Upload the new .smx file and delete the old one.

Do I even need the .sp file on the server? I assume not?

Thank you for helping a beginner like me once again!

**Comment by Sarrus1** [comment]
> Do I even need the .sp file on the server? I assume not?
No, but it's useful to keep them there to keep track of the sourcecode of the plugins you have on your server.

And yes, you got it right 👍 

> Thank you for helping a beginner like me once again!
No problem, I was there once ;)

**Comment by e1xom** [comment]
![image](https://user-images.githubusercontent.com/81571467/112873952-93a43700-90c2-11eb-99e5-6c9fc7aa7da7.png)

Not sure what I did wrong to get this error?

**Comment by Sarrus1** [comment]
I've uploaded a compiled binary [https://github.com/Sarrus1/retakes-instadefuse/blob/master/plugins/retakes-instadefuse.smx](here).

The error you got means the .smx file got corrupted somehow.

**Comment by e1xom** [comment]
> 
> 
> I've uploaded a compiled binary [here](https://github.com/Sarrus1/retakes-instadefuse/blob/master/plugins/retakes-instadefuse.smx).
> 
> The error you got means the .smx file got corrupted somehow.

Seems like I did something wrong, not sure what. But it shows up loaded now, will report back shortly if the mapvote is working. Thank you for all your effort :)

**Comment by crashzk** [comment]
https://github.com/b3none/retakes-instadefuse/releases/tag/1.4.0
