### ISSUE TITLE
1.4.0 [SM] Exception reported: Language phrase "InstaDefuseSuccessful" not found (arg 5)

### ISSUE THREAD

**Issue by zahti** [b3none/retakes-instadefuse#25]
**Describe the bug**
Using the pre-compiled 1.4.0 release does not work on a CS:GO retakes server. I got your autoplant plugin working with no issues (amazing btw!), but the instadefuse doesn't seem to do anything. There are some error messages seen in console - shown below in screenshot.

**Workaround**
I know this isn't what you want to hear - I saw some discussion on allied forums, but this plugin just worked for me with no hiccups https://forums.alliedmods.net/showthread.php?p=2558854
Please let me know if / when you update and I can test yours for you and start using yours :) 

**To Reproduce**
I have placed the 1.4.0 compiled release (**retakes-instadefuse.smx**) directly in the /addons/sourcemod/plugins folder.
Restarted server.
![2020-03-26 11_31_10-5e7bd101988b2559ec104cff@qyburn dathost net - FileZilla](https://user-images.githubusercontent.com/38710634/77677599-8acfd100-6f55-11ea-94ef-5a8fefe917f5.png)

Here are some console messages seen when someone goes to defuse:
![image](https://user-images.githubusercontent.com/38710634/77678177-632d3880-6f56-11ea-9f7a-9016dd24cf4f.png)

**Comment by TandelK** [comment]
As it clearly says it is looking for translations file which is missing or does not have read execute permissions. Please check accordingly.

**Comment by zahti** [comment]
@TandelK I didn't realize that line was for missing translations, thanks for the information. Where should that be located? I haven't ever touched the translation files.

**Comment by TandelK** [comment]
It is located in Releases tab when you download Plugin

**Comment by zahti** [comment]
@TandelK during installation, the only thing that I did was copy/paste the .smx file into the Addons folder. Why would I need to copy/paste the Translations file from the source code? Shouldn't the plugin generate that automatically?

> I have placed the 1.4.0 compiled release (retakes-instadefuse.smx) directly in the /addons/sourcemod/plugins folder.
Restarted server.

**Comment by TandelK** [comment]
@zahti Translations files are never generated . They have to be always used and the server only creates configuration file in cfg/sourcemod which is different thing. Remember this everytime you do something with new plugins always copy all the files properly. Even retake while installation uses Translations folder. Always keep in mind while copying files to CSGO Server always copy scripting as well as translations folder for specific plugin as they are dependent on it.

**Comment by zahti** [comment]
Adding the translations to the server files at /addons/sourcemod/translations has fixed this error message. Thanks for the help @TandelK
