### ISSUE TITLE
bug score 

### ISSUE THREAD

**Issue by d0kt0r** [b3none/retakes-instadefuse#3]
Hello! Again, the problem with the score, instead of 30 rounds is 40-50

**Comment by d0kt0r** [comment]
![30rounds](https://user-images.githubusercontent.com/5817389/52081704-fa456d00-25ab-11e9-8607-2f0af0d80881.png)

**Comment by b3none** [comment]
Hey, if you'd like you can speak to me on Discord as that might be an easier way to get to the root of the problem.

B3none #0575

**Comment by b3none** [comment]
I highly suspect that the round limiting problem isn't with this plugin.
