### ISSUE TITLE
Defuse time bug

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [b3none/retakes-instadefuse#4]
I think there might be a bug in the defuse plugin
4.5 seconds left to defuse and CT wins. It should take 5 or 10 seconds to defuse right?
![4b85ee0e1012b1de258ae36be5c9dbdc-png](https://user-images.githubusercontent.com/3598735/53012541-87f5d900-3443-11e9-9ab0-88a685c4be98.jpg)

**Comment by b3none** [comment]
That's definitely a bug, will look into this now.

**Comment by BrutalCSEjziponken** [comment]
It was overpass if that makes a difference

**Comment by b3none** [comment]
Looks like this was caused because the calculation I do to work out time left as well as the defusal time left are different.

```
float c4TimeLeft = GetConVarFloat(FindConVar("mp_c4timer")) - (GetGameTime() - g_c4PlantTime);
	
if(GetConVarInt(hEndIfTooLate) == 1 && GetEntPropFloat(c4, Prop_Send, "m_flC4Blow") < GetEntPropFloat(c4, Prop_Send, "m_flDefuseCountDown")) { ... }
```

**Comment by b3none** [comment]
Fixed in https://github.com/b3none/retakes-instadefuse/commit/fd905a6d9b420c149881cef8ce1cfedeb878342c
