### ISSUE TITLE
[Feature Request] Implement translations

### ISSUE THREAD

**Issue by shmidtelson** [b3none/retakes-instadefuse#5]
I am use this plugin for Russian servers. Thank you

**Comment by b3none** [comment]
I’ll look at implementing translations over the next week. Thanks for using the plugin! 🙂

**Comment by b3none** [comment]
Hey @shmidtelson please test the changes I've uploaded. I will also need you to provide Russian translations too.

**Comment by shmidtelson** [comment]
All right!
